Update dependencies
osisoft/sample-adh-authentication_authorization-nodejs pull request #22
Opened 2022-02-16 08:09 UTC by anton-dahlin

2022-02-17 17:32 UTC, cbardini commented
Is there more that needs to be updated besides the package-lock.json?

2022-02-18 09:25 UTC, anton-dahlin commented
> Is there more that needs to be updated besides the package-lock.json?

I resolved this using npm audit (https://docs.npmjs.com/cli/v8/commands/npm-audit) to find the vulnerability, then npm audit fix generate the fix, since this is a transient dependency there isn't anything to change in the package file so would assume that's why it only updated the lock file.

2022-02-22 21:15 UTC, kelseyduffy requested changes
package.json still says 1.2.0

2022-02-24 15:34 UTC, cbardini approved these changes

2022-02-25 13:08 UTC, derekendres approved these changes

2022-02-25 13:09 UTC, merged